- name: Run SeatGeek scraper
        run: cd scrapers && node seatgeek.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}
        continue-on-error: true

      - name: Run VividSeats scraper
        run: cd scrapers && node vivid.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}
        continue-on-error: true
